/* ============================================================
   CAMPUS CORE – DATA.JS
   All hardcoded demo data matching DPS Nadergul prototype
   ============================================================ */

// ─── Demo Users (Matching prototype credentials) ────────────
const DEMO_USERS = [
  {
    id: 1,
    username: "VP001",
    password: "VP123",
    name: "SUMAN",
    role: "vice_principal",
    roleLabel: "Vice Principal",
    department: "Executive Office",
    phone: "+91 98765 43210",
    email: "vp@dpsnadergul.edu",
    joined: "Mar 2019",
    avatar_color: "#2d7a6e",
    icon: "fa-user-tie",
    notifications: [
      { title: "Monthly Report Ready", text: "March 2026 analytics summary is ready for review", time: "30m ago", icon: "📊", color: "#5ca870" },
      { title: "Board Meeting", text: "Scheduled for April 5th, 2026 at 10 AM", time: "2h ago", icon: "📋", color: "#1976d2" },
      { title: "New Teacher Joined", text: "Ms. Pooja Mehta joined as Biology faculty", time: "1d ago", icon: "👩‍🏫", color: "#7ec490" },
      { title: "Audit Complete", text: "Annual infrastructure audit completed successfully", time: "2d ago", icon: "✅", color: "#4caf50" },
    ]
  },
  {
    id: 2,
    username: "T001",
    password: "teacher123",
    name: "Prasana Reddy",
    role: "teacher",
    roleLabel: "Teacher",
    department: "Mathematics",
    phone: "+91 87654 32109",
    email: "sneha@dpsnadergul.edu",
    joined: "Aug 2022",
    avatar_color: "#5ca870",
    icon: "fa-chalkboard-teacher",
    notifications: [
      { title: "Assignment Due Today", text: "Class 9B Quadratic Equations due by 3 PM", time: "1h ago", icon: "📝", color: "#f57c00" },
      { title: "Parent Query", text: "Parent sent a query about KASULA ASHWATH", time: "3h ago", icon: "💬", color: "#1976d2" },
      { title: "Marks Uploaded", text: "Mid-term marks for Class 10A uploaded successfully", time: "1d ago", icon: "✅", color: "#5ca870" },
    ]
  },
  {
    id: 5,
    username: "C001",
    password: "coord123",
    name: "Anitha",
    role: "coordinator",
    roleLabel: "Coordinator",
    department: "Academic Coordination",
    phone: "+91 54321 09876",
    email: "anitha@dpsnadergul.edu",
    joined: "Jun 2021",
    avatar_color: "#1976d2",
    icon: "fa-sitemap",
    notifications: [
      { title: "Timetable Updated", text: "Class 8 schedule revised for April", time: "1h ago", icon: "📅", color: "#1976d2" },
      { title: "Teacher On Leave", text: "Mr. Ramesh Sharma on leave tomorrow", time: "4h ago", icon: "👨‍🏫", color: "#f57c00" },
      { title: "CCA Event", text: "Science Exhibition registration deadline approaching", time: "1d ago", icon: "🔬", color: "#5ca870" },
    ]
  },
  {
    id: 6,
    username: "CT8B",
    password: "CLASS123",
    name: "Anita Pillai",
    role: "class_teacher",
    roleLabel: "Class Teacher",
    department: "English Literature",
    phone: "+91 43210 98765",
    email: "anita@dpsnadergul.edu",
    joined: "Jul 2020",
    avatar_color: "#8b5cf6",
    icon: "fa-user-graduate",
    notifications: [
      { title: "Report Cards Due", text: "8B report cards need to be generated by April 10", time: "2h ago", icon: "📋", color: "#f57c00" },
      { title: "Attendance Marked", text: "Today's attendance for 8B recorded successfully", time: "5h ago", icon: "✅", color: "#5ca870" },
      { title: "Parent Meeting", text: "Meeting scheduled with Nanda S. on April 3", time: "1d ago", icon: "👥", color: "#1976d2" },
    ]
  },
  {
    id: 7,
    username: "PRIN001",
    password: "PRINCIPAL123",
    name: "Principal",
    role: "principal",
    roleLabel: "Principal",
    department: "Principal's Office",
    phone: "+91 98765 00001",
    email: "principal@dpsnadergul.edu",
    joined: "Jan 2015",
    avatar_color: "#1a237e",
    icon: "fa-user-shield",
    notifications: [
      { title: "Board Meeting", text: "Scheduled for April 10th at 11 AM", time: "1h ago", icon: "📋", color: "#1976d2" },
      { title: "Annual Results", text: "Class 10 board results summary ready", time: "3h ago", icon: "📊", color: "#5ca870" },
      { title: "Staff Review", text: "Monthly staff performance review due", time: "1d ago", icon: "👥", color: "#f57c00" }
    ]
  },
  {
    id: 8,
    username: "APAAAS",
    password: "APAAAS",
    name: "Admin",
    role: "super_admin",
    roleLabel: "Super Admin",
    department: "System Administration",
    phone: "+91 98765 00002",
    email: "admin@dpsnadergul.edu",
    joined: "Jan 2020",
    avatar_color: "#1b5e20",
    icon: "fa-user-cog",
    notifications: [
      { title: "System Health", text: "All systems operational", time: "30m ago", icon: "✅", color: "#5ca870" },
      { title: "New User Added", text: "CT8B class teacher account created", time: "2h ago", icon: "👤", color: "#1976d2" },
      { title: "Storage Usage", text: "localStorage usage at 45%", time: "1d ago", icon: "💾", color: "#f57c00" }
    ]
  },
  {
    username: "P3180076A",
    password: "parent123",
    name: "Parent of KASULA ASHWATH",
    role: "parent",
    roleLabel: "Parent",
    department: "Parent of KASULA ASHWATH (Class 9-C)",
    childName: "KASULA ASHWATH",
    childClass: "9-C",
    childRoll: "07",
    avatar_color: "#f57c00",
    icon: "fa-user-friends",
    notifications: [
      { title: "Attendance Alert", text: "KASULA ASHWATH was absent on 27 March 2026", time: "1d ago", icon: "⚠️", color: "#d32f2f" },
      { title: "Fee Reminder", text: "April fee ₹10,000 due on 5th April", time: "2d ago", icon: "💰", color: "#f57c00" },
      { title: "Results Published", text: "Mid-term examination results are now available", time: "3d ago", icon: "📊", color: "#5ca870" },
    ]
  },
  { username: "P3160136A", password: "parent123", name: "Parent of PRANEETH BHUKYA", role: "parent", roleLabel: "Parent", department: "Parent of PRANEETH BHUKYA (Class 9-C)", childName: "PRANEETH BHUKYA", childClass: "9-C", childRoll: "01", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3160417A", password: "parent123", name: "Parent of SATHWIK REDDY GANTA", role: "parent", roleLabel: "Parent", department: "Parent of SATHWIK REDDY GANTA (Class 9-C)", childName: "SATHWIK REDDY GANTA", childClass: "9-C", childRoll: "02", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3160662A", password: "parent123", name: "Parent of KOTHA ASHVIK", role: "parent", roleLabel: "Parent", department: "Parent of KOTHA ASHVIK (Class 9-C)", childName: "KOTHA ASHVIK", childClass: "9-C", childRoll: "03", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3170292A", password: "parent123", name: "Parent of BOPPARAJU ABHIRAM", role: "parent", roleLabel: "Parent", department: "Parent of BOPPARAJU ABHIRAM (Class 9-C)", childName: "BOPPARAJU ABHIRAM", childClass: "9-C", childRoll: "04", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3170355A", password: "parent123", name: "Parent of BOYINI VIVEKANANDA MUDIRAJ", role: "parent", roleLabel: "Parent", department: "Parent of BOYINI VIVEKANANDA MUDIRAJ (Class 9-C)", childName: "BOYINI VIVEKANANDA MUDIRAJ", childClass: "9-C", childRoll: "05", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3170390A", password: "parent123", name: "Parent of LOLLA ABHIRAM", role: "parent", roleLabel: "Parent", department: "Parent of LOLLA ABHIRAM (Class 9-C)", childName: "LOLLA ABHIRAM", childClass: "9-C", childRoll: "06", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3180133A", password: "parent123", name: "Parent of SNITHIK VENGALA", role: "parent", roleLabel: "Parent", department: "Parent of SNITHIK VENGALA (Class 9-C)", childName: "SNITHIK VENGALA", childClass: "9-C", childRoll: "08", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3180183A", password: "parent123", name: "Parent of NIDHISH DUMALA", role: "parent", roleLabel: "Parent", department: "Parent of NIDHISH DUMALA (Class 9-C)", childName: "NIDHISH DUMALA", childClass: "9-C", childRoll: "09", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3180184A", password: "parent123", name: "Parent of YAMMANURU HARITEJA", role: "parent", roleLabel: "Parent", department: "Parent of YAMMANURU HARITEJA (Class 9-C)", childName: "YAMMANURU HARITEJA", childClass: "9-C", childRoll: "10", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3180286A", password: "parent123", name: "Parent of CHARAN BATTU", role: "parent", roleLabel: "Parent", department: "Parent of CHARAN BATTU (Class 9-C)", childName: "CHARAN BATTU", childClass: "9-C", childRoll: "11", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3190472A", password: "parent123", name: "Parent of ATHUL M", role: "parent", roleLabel: "Parent", department: "Parent of ATHUL M (Class 9-C)", childName: "ATHUL M", childClass: "9-C", childRoll: "12", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3200320A", password: "parent123", name: "Parent of SIDDHARTH REDDY SADIVILLA", role: "parent", roleLabel: "Parent", department: "Parent of SIDDHARTH REDDY SADIVILLA (Class 9-C)", childName: "SIDDHARTH REDDY SADIVILLA", childClass: "9-C", childRoll: "13", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3200437A", password: "parent123", name: "Parent of SIDDALA RAMCHARAN", role: "parent", roleLabel: "Parent", department: "Parent of SIDDALA RAMCHARAN (Class 9-C)", childName: "SIDDALA RAMCHARAN", childClass: "9-C", childRoll: "14", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3210447A", password: "parent123", name: "Parent of SAPAVATH JAHNAVI", role: "parent", roleLabel: "Parent", department: "Parent of SAPAVATH JAHNAVI (Class 9-C)", childName: "SAPAVATH JAHNAVI", childClass: "9-C", childRoll: "15", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3210590A", password: "parent123", name: "Parent of K MOKSHA", role: "parent", roleLabel: "Parent", department: "Parent of K MOKSHA (Class 9-C)", childName: "K MOKSHA", childClass: "9-C", childRoll: "16", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3230302A", password: "parent123", name: "Parent of BOJJA HARIKESH REDDY", role: "parent", roleLabel: "Parent", department: "Parent of BOJJA HARIKESH REDDY (Class 9-C)", childName: "BOJJA HARIKESH REDDY", childClass: "9-C", childRoll: "17", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3230706A", password: "parent123", name: "Parent of EKADANTHA YADAV", role: "parent", roleLabel: "Parent", department: "Parent of EKADANTHA YADAV (Class 9-C)", childName: "EKADANTHA YADAV", childClass: "9-C", childRoll: "18", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3240214A", password: "parent123", name: "Parent of NIMMAKAYALA PRATEEK REDDY", role: "parent", roleLabel: "Parent", department: "Parent of NIMMAKAYALA PRATEEK REDDY (Class 9-C)", childName: "NIMMAKAYALA PRATEEK REDDY", childClass: "9-C", childRoll: "19", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3240504A", password: "parent123", name: "Parent of CHEEKOORI SAI CHARAN", role: "parent", roleLabel: "Parent", department: "Parent of CHEEKOORI SAI CHARAN (Class 9-C)", childName: "CHEEKOORI SAI CHARAN", childClass: "9-C", childRoll: "20", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3240693A", password: "parent123", name: "Parent of VALLETI SAI HARSHITH", role: "parent", roleLabel: "Parent", department: "Parent of VALLETI SAI HARSHITH (Class 9-C)", childName: "VALLETI SAI HARSHITH", childClass: "9-C", childRoll: "21", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3250112A", password: "parent123", name: "Parent of P SATHWIK REDDY", role: "parent", roleLabel: "Parent", department: "Parent of P SATHWIK REDDY (Class 9-C)", childName: "P SATHWIK REDDY", childClass: "9-C", childRoll: "22", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3260066A", password: "parent123", name: "Parent of DEPA AARYAN REDDY", role: "parent", roleLabel: "Parent", department: "Parent of DEPA AARYAN REDDY (Class 9-C)", childName: "DEPA AARYAN REDDY", childClass: "9-C", childRoll: "23", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3230719A", password: "parent123", name: "Parent of G MANASWINI", role: "parent", roleLabel: "Parent", department: "Parent of G MANASWINI (Class 9-C)", childName: "G MANASWINI", childClass: "9-C", childRoll: "24", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3170068A", password: "parent123", name: "Parent of SHERI RITHIK REDDY", role: "parent", roleLabel: "Parent", department: "Parent of SHERI RITHIK REDDY (Class 9-C)", childName: "SHERI RITHIK REDDY", childClass: "9-C", childRoll: "25", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3220915A", password: "parent123", name: "Parent of BHUKYA PRANAVI", role: "parent", roleLabel: "Parent", department: "Parent of BHUKYA PRANAVI (Class 9-C)", childName: "BHUKYA PRANAVI", childClass: "9-C", childRoll: "26", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
  { username: "P3190133A", password: "parent123", name: "Parent of TANABUDDI SRI BHAVESH REDDY", role: "parent", roleLabel: "Parent", department: "Parent of TANABUDDI SRI BHAVESH REDDY (Class 9-C)", childName: "TANABUDDI SRI BHAVESH REDDY", childClass: "9-C", childRoll: "27", avatar_color: "#f57c00", icon: "fa-user-friends", notifications: [] },
];

// ─── Students ────────────────────────────────────────────────
let STUDENTS = [
  { id: "3180076", admNo: "3180076", name: "KASULA ASHWATH", class: "9-C", roll: "07", gender: "Unknown", dob: "15 Jan 2011", attendance: 91, behavior: "Good", fee_status: "Partial", gpa: 8.7, parent: "Parent of KASULA ASHWATH" },
  { id: "3160136", admNo: "3160136", name: "PRANEETH BHUKYA", class: "9-C", roll: "01", gender: "Unknown", dob: "15 Jan 2011", attendance: 86, behavior: "Good", fee_status: "Paid", gpa: 7.6, parent: "Parent of PRANEETH BHUKYA" },
  { id: "3160417", admNo: "3160417", name: "SATHWIK REDDY GANTA", class: "9-C", roll: "02", gender: "Unknown", dob: "15 Jan 2011", attendance: 87, behavior: "Good", fee_status: "Paid", gpa: 7.7, parent: "Parent of SATHWIK REDDY GANTA" },
  { id: "3160662", admNo: "3160662", name: "KOTHA ASHVIK", class: "9-C", roll: "03", gender: "Unknown", dob: "15 Jan 2011", attendance: 88, behavior: "Good", fee_status: "Paid", gpa: 7.8, parent: "Parent of KOTHA ASHVIK" },
  { id: "3170292", admNo: "3170292", name: "BOPPARAJU ABHIRAM", class: "9-C", roll: "04", gender: "Unknown", dob: "15 Jan 2011", attendance: 89, behavior: "Good", fee_status: "Paid", gpa: 7.9, parent: "Parent of BOPPARAJU ABHIRAM" },
  { id: "3170355", admNo: "3170355", name: "BOYINI VIVEKANANDA MUDIRAJ", class: "9-C", roll: "05", gender: "Unknown", dob: "15 Jan 2011", attendance: 90, behavior: "Good", fee_status: "Paid", gpa: 8.0, parent: "Parent of BOYINI VIVEKANANDA MUDIRAJ" },
  { id: "3170390", admNo: "3170390", name: "LOLLA ABHIRAM", class: "9-C", roll: "06", gender: "Unknown", dob: "15 Jan 2011", attendance: 91, behavior: "Good", fee_status: "Paid", gpa: 8.1, parent: "Parent of LOLLA ABHIRAM" },
  { id: "3180133", admNo: "3180133", name: "SNITHIK VENGALA", class: "9-C", roll: "08", gender: "Unknown", dob: "15 Jan 2011", attendance: 93, behavior: "Good", fee_status: "Paid", gpa: 8.3, parent: "Parent of SNITHIK VENGALA" },
  { id: "3180183", admNo: "3180183", name: "NIDHISH DUMALA", class: "9-C", roll: "09", gender: "Unknown", dob: "15 Jan 2011", attendance: 94, behavior: "Good", fee_status: "Paid", gpa: 8.4, parent: "Parent of NIDHISH DUMALA" },
  { id: "3180184", admNo: "3180184", name: "YAMMANURU HARITEJA", class: "9-C", roll: "10", gender: "Unknown", dob: "15 Jan 2011", attendance: 95, behavior: "Good", fee_status: "Paid", gpa: 8.5, parent: "Parent of YAMMANURU HARITEJA" },
  { id: "3180286", admNo: "3180286", name: "CHARAN BATTU", class: "9-C", roll: "11", gender: "Unknown", dob: "15 Jan 2011", attendance: 96, behavior: "Good", fee_status: "Paid", gpa: 8.6, parent: "Parent of CHARAN BATTU" },
  { id: "3190472", admNo: "3190472", name: "ATHUL M", class: "9-C", roll: "12", gender: "Unknown", dob: "15 Jan 2011", attendance: 97, behavior: "Good", fee_status: "Paid", gpa: 8.7, parent: "Parent of ATHUL M" },
  { id: "3200320", admNo: "3200320", name: "SIDDHARTH REDDY SADIVILLA", class: "9-C", roll: "13", gender: "Unknown", dob: "15 Jan 2011", attendance: 98, behavior: "Good", fee_status: "Paid", gpa: 8.8, parent: "Parent of SIDDHARTH REDDY SADIVILLA" },
  { id: "3200437", admNo: "3200437", name: "SIDDALA RAMCHARAN", class: "9-C", roll: "14", gender: "Unknown", dob: "15 Jan 2011", attendance: 99, behavior: "Good", fee_status: "Paid", gpa: 8.9, parent: "Parent of SIDDALA RAMCHARAN" },
  { id: "3210447", admNo: "3210447", name: "SAPAVATH JAHNAVI", class: "9-C", roll: "15", gender: "Unknown", dob: "15 Jan 2011", attendance: 85, behavior: "Good", fee_status: "Paid", gpa: 9.0, parent: "Parent of SAPAVATH JAHNAVI" },
  { id: "3210590", admNo: "3210590", name: "K MOKSHA", class: "9-C", roll: "16", gender: "Unknown", dob: "15 Jan 2011", attendance: 86, behavior: "Good", fee_status: "Paid", gpa: 9.1, parent: "Parent of K MOKSHA" },
  { id: "3230302", admNo: "3230302", name: "BOJJA HARIKESH REDDY", class: "9-C", roll: "17", gender: "Unknown", dob: "15 Jan 2011", attendance: 87, behavior: "Good", fee_status: "Paid", gpa: 9.2, parent: "Parent of BOJJA HARIKESH REDDY" },
  { id: "3230706", admNo: "3230706", name: "EKADANTHA YADAV", class: "9-C", roll: "18", gender: "Unknown", dob: "15 Jan 2011", attendance: 88, behavior: "Good", fee_status: "Paid", gpa: 9.3, parent: "Parent of EKADANTHA YADAV" },
  { id: "3240214", admNo: "3240214", name: "NIMMAKAYALA PRATEEK REDDY", class: "9-C", roll: "19", gender: "Unknown", dob: "15 Jan 2011", attendance: 89, behavior: "Good", fee_status: "Paid", gpa: 9.4, parent: "Parent of NIMMAKAYALA PRATEEK REDDY" },
  { id: "3240504", admNo: "3240504", name: "CHEEKOORI SAI CHARAN", class: "9-C", roll: "20", gender: "Unknown", dob: "15 Jan 2011", attendance: 90, behavior: "Good", fee_status: "Paid", gpa: 7.5, parent: "Parent of CHEEKOORI SAI CHARAN" },
  { id: "3240693", admNo: "3240693", name: "VALLETI SAI HARSHITH", class: "9-C", roll: "21", gender: "Unknown", dob: "15 Jan 2011", attendance: 91, behavior: "Good", fee_status: "Paid", gpa: 7.6, parent: "Parent of VALLETI SAI HARSHITH" },
  { id: "3250112", admNo: "3250112", name: "P SATHWIK REDDY", class: "9-C", roll: "22", gender: "Unknown", dob: "15 Jan 2011", attendance: 92, behavior: "Good", fee_status: "Paid", gpa: 7.7, parent: "Parent of P SATHWIK REDDY" },
  { id: "3260066", admNo: "3260066", name: "DEPA AARYAN REDDY", class: "9-C", roll: "23", gender: "Unknown", dob: "15 Jan 2011", attendance: 93, behavior: "Good", fee_status: "Paid", gpa: 7.8, parent: "Parent of DEPA AARYAN REDDY" },
  { id: "3230719", admNo: "3230719", name: "G MANASWINI", class: "9-C", roll: "24", gender: "Unknown", dob: "15 Jan 2011", attendance: 94, behavior: "Good", fee_status: "Paid", gpa: 7.9, parent: "Parent of G MANASWINI" },
  { id: "3170068", admNo: "3170068", name: "SHERI RITHIK REDDY", class: "9-C", roll: "25", gender: "Unknown", dob: "15 Jan 2011", attendance: 95, behavior: "Good", fee_status: "Paid", gpa: 8.0, parent: "Parent of SHERI RITHIK REDDY" },
  { id: "3220915", admNo: "3220915", name: "BHUKYA PRANAVI", class: "9-C", roll: "26", gender: "Unknown", dob: "15 Jan 2011", attendance: 96, behavior: "Good", fee_status: "Paid", gpa: 8.1, parent: "Parent of BHUKYA PRANAVI" },
  { id: "3190133", admNo: "3190133", name: "TANABUDDI SRI BHAVESH REDDY", class: "9-C", roll: "27", gender: "Unknown", dob: "15 Jan 2011", attendance: 97, behavior: "Good", fee_status: "Paid", gpa: 8.2, parent: "Parent of TANABUDDI SRI BHAVESH REDDY" },
];

// ─── Teachers ────────────────────────────────────────────────
const TEACHERS = [
  { id: "T001", name: "Prasana Reddy",   subject: "Mathematics",       classes: "10-A, 9-B",  exp: "8 years",  phone: "+91 87654 11111", status: "Active" },
  { id: "T002", name: "Ramesh Sharma",   subject: "Physics",           classes: "10-A, 10-B", exp: "12 years", phone: "+91 87654 22222", status: "Active" },
  { id: "T003", name: "Anita Pillai",    subject: "English Literature",classes: "8-B, 9-A",   exp: "6 years",  phone: "+91 87654 33333", status: "Active" },
  { id: "T004", name: "Mohan Das",       subject: "Chemistry",         classes: "10-C, 9-D", exp: "15 years", phone: "+91 87654 44444", status: "Active" },
  { id: "T005", name: "Sunita Verma",    subject: "History",           classes: "7-A, 6-B",   exp: "9 years",  phone: "+91 87654 55555", status: "Active" },
  { id: "T006", name: "Venkat Iyer",     subject: "Computer Science",  classes: "8-A, 9-C",   exp: "5 years",  phone: "+91 87654 66666", status: "Active" },
  { id: "T007", name: "Pooja Mehta",     subject: "Biology",           classes: "8-E, 9-F", exp: "7 years",  phone: "+91 87654 77777", status: "Active" },
  { id: "T008", name: "Suresh Naidu",    subject: "Physical Education",classes: "All",         exp: "11 years", phone: "+91 87654 88888", status: "Active" },
];


// --- GLOBAL DATA COLLECTIONS ---

// ─── Attendance Data ─────────────────────────────────────────
const ATTENDANCE_SUMMARY = {
  total_students: 540,
  present_today: 496,
  absent_today: 36,
  late_today: 8,
  weekly: [
    { day: "Mon", present: 92, total: 100 },
    { day: "Tue", present: 88, total: 100 },
    { day: "Wed", present: 95, total: 100 },
    { day: "Thu", present: 78, total: 100 },
    { day: "Fri", present: 91, total: 100 },
    { day: "Sat", present: 70, total: 100 },
  ],
};

// ─── Recent Activity ────────────────────────────────────────
const RECENT_ACTIVITY = [
  { text: "New student Priya S. enrolled in Class 10-A",       time: "2 min ago",  color: "#5ca870", icon: "🎓" },
  { text: "Prasana Reddy submitted marks for Class 10-A",     time: "15 min ago", color: "#1976d2", icon: "📝" },
  { text: "Fee payment received from Mohan Menon – ₹5,000",   time: "1 hr ago",   color: "#f57c00", icon: "💰" },
  { text: "Homework 'Periodic Table Quiz' marked complete",    time: "2 hr ago",   color: "#4caf50", icon: "✅" },
  { text: "G MANASWINI attendance flagged – 79% (below 80%)",  time: "3 hr ago",   color: "#d32f2f", icon: "⚠️" },
  { text: "Annual Sports Day notice published by VP",          time: "5 hr ago",   color: "#8b5cf6", icon: "📢" },
  { text: "Timetable updated for Class 8-B by coordinator",    time: "6 hr ago",   color: "#00bcd4", icon: "📅" },
];

// ─── Role Navigation Config ──────────────────────────────────
const ROLE_NAV = {
  vice_principal: [
    { label: "Main", items: [
      { id: "home",              icon: "fa-tachometer-alt",     label: "Dashboard" },
      { id: "profile",           icon: "fa-user-circle",        label: "My Profile" },
    ]},
    { label: "Academic Ops", items: [
      { id: "vp_attendance",     icon: "fa-clipboard-check",    label: "Attendance Overview" },
      { id: "vp_class_perf",     icon: "fa-chart-pie",          label: "Class Performance" },
      { id: "vp_students",       icon: "fa-chart-line",         label: "Student Analysis" },
      { id: "vp_student_issues", icon: "fa-exclamation-triangle",label:"Student Issues", badge: "2" },
      { id: "vp_approvals",      icon: "fa-check-double",       label: "Approvals", badge: "5" },
      { id: "document_upload",    icon: "fa-upload",             label: "Upload Document" },
      { id: "helpdesk_staff",     icon: "fa-headset",            label: "Helpdesk Tickets" },
    ]},
    { label: "Staff Ops", items: [
      { id: "vp_teachers",       icon: "fa-chalkboard-teacher", label: "Teacher Monitoring" },
      { id: "vp_schedule",       icon: "fa-calendar-alt",       label: "Timetable Review", badge: "1" },
    ]},
    { label: "Examination", items: [
      { id: "vp_exams",          icon: "fa-file-signature",     label: "Exams & Results" },
      { id: "vp_reports",        icon: "fa-chart-bar",          label: "Reports" },
    ]},
    { label: "Logistics & Comms", items: [
      { id: "vp_approvals",      icon: "fa-check-circle",       label: "Approvals", badge: "5" },
      { id: "announcements",     icon: "fa-bullhorn",           label: "Notices" },
      { id: "events",            icon: "fa-calendar-star",      label: "Events" },
      { id: "vp_messages",       icon: "fa-envelope",           label: "Messages", badge: "3" },
    ]},
    { label: "System", items: [
      { id: "settings",          icon: "fa-cog",                label: "Settings" },
    ]},
  ],
  teacher: [
    { label: "Main", items: [
      { id: "home",              icon: "fa-tachometer-alt",     label: "Dashboard" },
      { id: "teacher_classes",   icon: "fa-chalkboard",         label: "My Classes" },
    ]},
    { label: "Academics", items: [
      { id: "teacher_attendance",icon: "fa-clipboard-check",    label: "Attendance" },
      { id: "teacher_homework",  icon: "fa-book-open",          label: "Homework" },
      { id: "teacher_schedule",  icon: "fa-calendar-alt",       label: "Timetable" },
      { id: "teacher_results",   icon: "fa-chart-bar",          label: "Marks & Results" },
      { id: "teacher_performance",icon:"fa-chart-line",         label: "Student Performance" },
    ]},
    { label: "School", items: [
      { id: "announcements",     icon: "fa-bullhorn",           label: "Notices" },
      { id: "teacher_messages",  icon: "fa-envelope",           label: "Messages", badge: "2" },
    ]},
    { label: "Account", items: [
      { id: "settings",          icon: "fa-cog",                label: "Profile & Settings" },
    ]},
  ],
  parent: [
    { label: "Main", items: [
      { id: "home",              icon: "fa-home",               label: "Dashboard" },
      { id: "parent_child",      icon: "fa-user-graduate",      label: "Child Profile" },
    ]},
    { label: "Academics", items: [
      { id: "parent_attendance",  icon: "fa-clipboard-check",    label: "Attendance" },
      { id: "parent_homework",    icon: "fa-book-open",          label: "Homework" },
      { id: "parent_exams",       icon: "fa-calendar-alt",       label: "Exam Schedule" },
      { id: "parent_results",     icon: "fa-chart-bar",          label: "Results" },
    ]},
    { label: "Finance", items: [
      { id: "parent_fees",        icon: "fa-rupee-sign",         label: "Fees & Payments" },
    ]},
    { label: "School & Help", items: [
      { id: "announcements",      icon: "fa-bullhorn",           label: "Notices" },
      { id: "events",             icon: "fa-calendar-star",      label: "Events" },
      { id: "parent_messages",    icon: "fa-envelope",           label: "Messages & Concerns" },
    ]},
    { label: "Account", items: [
      { id: "settings",           icon: "fa-cog",                label: "Portal Settings" },
    ]},
  ],
  coordinator: [
    { label: "Main", items: [
      { id: "home",          icon: "fa-tachometer-alt",     label: "Dashboard" },
      { id: "profile",       icon: "fa-user-circle",        label: "My Profile" },
    ]},
    { label: "Academic", items: [
      { id: "teachers",      icon: "fa-chalkboard-teacher", label: "Teachers" },
      { id: "schedule",      icon: "fa-calendar-alt",       label: "Timetable" },
      { id: "attendance",    icon: "fa-clipboard-check",    label: "Attendance" },
      { id: "homework",      icon: "fa-book-open",          label: "Homework" },
    ]},
    { label: "Communication", items: [
      { id: "announcements", icon: "fa-bullhorn",           label: "Notices" },
      { id: "events",        icon: "fa-calendar-star",      label: "Events & CCA" },
      { id: "results",       icon: "fa-chart-bar",          label: "Reports" },
      { id: "settings",      icon: "fa-cog",                label: "Settings" },
    ]},
  ],
  class_teacher: [
    { label: "Main", items: [
      { id: "home",          icon: "fa-tachometer-alt",     label: "Dashboard" },
      { id: "profile",       icon: "fa-user-circle",        label: "My Profile" },
    ]},
    { label: "My Class", items: [
      { id: "students",      icon: "fa-user-graduate",      label: "Class Students" },
      { id: "attendance",    icon: "fa-clipboard-check",    label: "Attendance" },
      { id: "homework",      icon: "fa-book-open",          label: "Homework" },
      { id: "results",       icon: "fa-chart-bar",          label: "Report Cards" },
      { id: "schedule",      icon: "fa-calendar-alt",       label: "Timetable" },
      { id: "document_upload", icon: "fa-upload",            label: "Upload Document" },
    ]},
    { label: "Communication/Support", items: [
      { id: "announcements", icon: "fa-bullhorn",           label: "Notices" },
      { id: "events",        icon: "fa-calendar-star",      label: "Events" },
      { id: "helpdesk_staff", icon: "fa-headset",           label: "Helpdesk Tickets" },
      { id: "settings",      icon: "fa-cog",                label: "Settings" },
    ]},
  ],
  principal: [
    { label: "Main", items: [
      { id: "home",              icon: "fa-tachometer-alt",     label: "Principal Dashboard" },
      { id: "profile",           icon: "fa-user-circle",        label: "My Profile" },
    ]},
    { label: "Institution Ops", items: [
      { id: "attendance_reports",icon: "fa-clipboard-check",    label: "Attendance Reports" },
      { id: "exam_results",      icon: "fa-file-signature",     label: "Exam Results" },
      { id: "class_performance", icon: "fa-chart-pie",          label: "Class Performance" },
      { id: "approvals",         icon: "fa-check-circle",       label: "Approvals", badge: "5" },
      { id: "document_upload",    icon: "fa-upload",             label: "Upload Document" },
    ]},
    { label: "Comms & Support", items: [
      { id: "notices",           icon: "fa-bullhorn",           label: "Notices" },
      { id: "events",            icon: "fa-calendar-star",      label: "Events" },
      { id: "messages",          icon: "fa-envelope",           label: "Messages", badge: "3" },
      { id: "helpdesk_staff",     icon: "fa-headset",            label: "Helpdesk Tickets" },
      { id: "settings",          icon: "fa-cog",                label: "Settings" },
    ]},
  ],
  apaaas: [
    { label: "Main", items: [
      { id: "master_dashboard",  icon: "fa-tachometer-alt",     label: "Master Dashboard" },
      { id: "role_views",        icon: "fa-users-cog",          label: "Role Views" },
    ]},
    { label: "System-wide Logs", items: [
      { id: "all_issues",        icon: "fa-exclamation-triangle",label: "All Issues", badge: "2" },
      { id: "all_notices",       icon: "fa-bullhorn",           label: "All Notices" },
      { id: "all_approvals",     icon: "fa-check-circle",       label: "All Approvals", badge: "5" },
      { id: "all_accounts",      icon: "fa-users",              label: "System Audit" },
      { id: "manage_documents",  icon: "fa-folder-open",        label: "Manage Documents" },
      { id: "removed_bin",       icon: "fa-trash-alt",          label: "Removed Bin" },
    ]},
    { label: "Activity & System", items: [
      { id: "all_attendance",    icon: "fa-clipboard-check",    label: "All Attendance" },
      { id: "all_results",       icon: "fa-file-signature",     label: "All Results" },
      { id: "all_messages",      icon: "fa-envelope",           label: "All Messages" },
      { id: "all_helpdesk",      icon: "fa-headset",            label: "Full Helpdesk" },
      { id: "settings",          icon: "fa-cog",                label: "Settings" },
    ]},
  ],
};
ROLE_NAV.super_admin = ROLE_NAV.apaaas;
ROLE_NAV.superadmin = ROLE_NAV.apaaas;

// ─── Dashboard Home Config Per Role ──────────────────────────
const ROLE_HOME = {
  vice_principal: {
    greeting: "Welcome back, Suman!",
    subtitle: "School operations, academic tracking, and staff monitoring overview.",
    stats: [
      { label: "School Attendance", value: "92.5%", icon: "📋", color: "#4caf50" },
      { label: "Teacher Presence",  value: "31/32", icon: "👨‍🏫", color: "#1976d2" },
      { label: "Pending Approvals", value: "5",     icon: "✅", color: "#f57c00" },
      { label: "Low Att. Classes",  value: "3",     icon: "📉", color: "#d32f2f" },
      { label: "Pending Marks",     value: "2",     icon: "📝", color: "#8b5cf6" },
      { label: "Discipline Cases",  value: "2",     icon: "⚠️", color: "#ff5722" },
      { label: "Upcoming Exams",    value: "3",     icon: "📅", color: "#00bcd4" },
      { label: "Active Notices",    value: "12",    icon: "📢", color: "#8b5cf6" },
    ]
  },
  teacher: {
    greeting: "Good Morning, Prasana!",
    subtitle: "Your classes and tasks for today.",
    stats: [
      { label: "Classes Today",     value: "4",   icon: "📚", color: "#1976d2" },
      { label: "Pending Attendance",value: "2",   icon: "📋", color: "#f57c00" },
      { label: "Assignments to Grade",value: "15",icon: "📝", color: "#d32f2f" },
      { label: "Upcoming Tests",    value: "1",   icon: "📅", color: "#8b5cf6" },
      { label: "Average Class Perf",value: "82%", icon: "🌟", color: "#5ca870" },
    ]
  },
  parent: {
    greeting: "Hello, Mr. Ashwath!",
    subtitle: "KASULA ASHWATH · Class 9-C · DPS Nadergul",
    stats: [
      { label: "Attendance",       value: "94%",  icon: "📋", color: "#5ca870" },
      { label: "Average Score",    value: "86%",  icon: "📊", color: "#1976d2" },
      { label: "Pending Homework", value: "2",    icon: "📝", color: "#f57c00" },
      { label: "Upcoming Exams",   value: "3",    icon: "📅", color: "#8b5cf6" },
      { label: "Latest Grade",     value: "A",    icon: "🏅", color: "#4caf50" },
      { label: "Fee Due",          value: "₹10K", icon: "💰", color: "#d32f2f" },
    ]
  },
  coordinator: {
    greeting: "Hello, Anitha!",
    subtitle: "Academic coordination dashboard.",
    stats: [
      { label: "Classes Managed",   value: "18", icon: "🏫", color: "#5ca870" },
      { label: "Teaching Staff",    value: "32", icon: "👨‍🏫", color: "#1976d2" },
      { label: "Notices Published", value: "12", icon: "📢", color: "#8b5cf6" },
      { label: "Open Issues",      value: "5",  icon: "⚠️", color: "#f57c00" },
    ]
  },
  class_teacher: {
    greeting: "Hello, Ms. Anita!",
    subtitle: "Class 8-B dashboard and attendance.",
    stats: [
      { label: "Class Strength",    value: "35",   icon: "🎓", color: "#5ca870" },
      { label: "Present Today",     value: "32",   icon: "✅", color: "#4caf50" },
      { label: "Absent Today",      value: "3",    icon: "❌", color: "#d32f2f" },
      { label: "Class Average",     value: "78%",  icon: "📊", color: "#1976d2" },
    ]
  },
  principal: {
    greeting: "Good Day, Principal Sir!",
    subtitle: "Institution-wide health, performance, and strategic overview.",
    stats: [
      { label: "Overall Attendance", value: "92.5%", icon: "📋", color: "#4caf50" },
      { label: "Academic Standing",  value: "8.4 avg", icon: "🌟", color: "#1976d2" },
      { label: "Teacher Fulfillment",value: "31/32", icon: "👩‍🏫", color: "#f57c00" },
      { label: "Strategic Approvals",value: "5",     icon: "⏱️", color: "#d32f2f" },
    ]
  },
  apaaas: {
    greeting: "Welcome, SuperAdmin!",
    subtitle: "Full-system audit and administrative control center.",
    stats: [
      { label: "Uptime Status",      value: "99.9%", icon: "⚡", color: "#4caf50" },
      { label: "Total Students",     value: "540+",  icon: "🎓", color: "#1976d2" },
      { label: "Active Sessions",    value: "14",    icon: "💻", color: "#f57c00" },
      { label: "Unresolved Issues",  value: "2",     icon: "🚨", color: "#d32f2f" },
    ]
  }
};
ROLE_HOME.super_admin = ROLE_HOME.apaaas;
ROLE_HOME.superadmin = ROLE_HOME.apaaas;

// ─── Vice Principal Specific Mock Data ───────────────────────

// --- REMOVED OLD VP_APPROVALS ---


const VP_MESSAGES = [
  { sender: "Anitha (Coord)", subject: "Class 9-B timetable clash resolved", time: "10:30 AM", unread: true, content: "The clash for period 3 science has been handled by swapping with Venkat Iyer." },
  { sender: "Prasana Reddy", subject: "Math syllabus completion report", time: "09:15 AM", unread: true, content: "Syllabus is on track. We are slightly behind in Trigonometry but covering up." },
  { sender: "Admin Office", subject: "Transport issue reported for Route 4", time: "Yesterday", unread: false, content: "Route 4 had a delay of 20 mins due to traffic." },
  { sender: "Nanda S. (Parent)", subject: "Meeting confirmation regarding Siddharth", time: "Yesterday", unread: false, content: "I'll be there at 10 AM tomorrow to discuss Siddharth's performance." },
];

const DISCIPLINE_CASES = [
  { student: "KASULA ASHWATH", class: "9-C", issue: "Continuous absence without notice", reporter: "Anitha", status: "Action Required", urgency: "High" },
  { student: "SATHWIK REDDY GANTA", class: "9-C", issue: "Disruptive behavior in Science Lab", reporter: "Pooja Mehta", status: "Under Observation", urgency: "Medium" },
  { student: "G MANASWINI", class: "9-C", issue: "Using mobile phone in classroom", reporter: "Ramesh Sharma", status: "Resolved", urgency: "Low" },
];


// --- REMOVED OLD CLASS_PERFORMANCE ---


// ─── Parent Specific Mock Data ───────────────────────────────
const PARENT_CHILD = {
  name: "KASULA ASHWATH",
  class: "9-C",
  roll: "07",
  admNo: "3180076",
  dob: "12 Apr 2009",
  gender: "Male",
  bloodGroup: "B+",
  classTeacher: "Prasana Reddy",
  house: "Ganga House",
  academicYear: "2025-2026",
  parentContact: "+91 76543 21098",
  parentEmail: "ashwath@gmail.com",
  parentName: "Parent of KASULA ASHWATH",
  attendance: 94,
  gpa: 8.7,
};

const PARENT_ATTENDANCE_LOG = [
  { date: "27 Mar 2026", status: "Absent", reason: "Fever" },
  { date: "26 Mar 2026", status: "Present", reason: "" },
  { date: "25 Mar 2026", status: "Present", reason: "" },
  { date: "24 Mar 2026", status: "Present", reason: "" },
  { date: "21 Mar 2026", status: "Late",    reason: "Transport delay" },
  { date: "20 Mar 2026", status: "Present", reason: "" },
  { date: "19 Mar 2026", status: "Present", reason: "" },
  { date: "18 Mar 2026", status: "Absent",  reason: "Family function" },
  { date: "17 Mar 2026", status: "Present", reason: "" },
  { date: "14 Mar 2026", status: "Present", reason: "" },
];

const PARENT_MONTHLY_ATT = [
  { month: "Oct", pct: 96 }, { month: "Nov", pct: 92 },
  { month: "Dec", pct: 90 }, { month: "Jan", pct: 94 },
  { month: "Feb", pct: 97 }, { month: "Mar", pct: 94 },
];

const PARENT_HOMEWORK = [
  { subject: "Mathematics", title: "Quadratic Equations – Practice Set A", due: "31 Mar 2026", teacher: "Prasana Reddy", status: "Pending" },
  { subject: "Physics",     title: "Newton's Laws – Lab Report",          due: "2 Apr 2026",  teacher: "Ramesh Sharma",  status: "Pending" },
  { subject: "Chemistry",   title: "Periodic Table Quiz",                 due: "28 Mar 2026", teacher: "Mohan Das",      status: "Completed" },
  { subject: "English",     title: "Essay – My Future Goals",              due: "25 Mar 2026", teacher: "Anita Pillai",   status: "Completed" },
  { subject: "History",     title: "Timeline of Indian Independence",     due: "5 Apr 2026",  teacher: "Sunita Verma",   status: "Pending" },
  { subject: "Comp. Sci",   title: "Python Basics – Program Set 1",       due: "10 Apr 2026", teacher: "Venkat Iyer",    status: "Not Started" },
];

const PARENT_EXAMS = [
  { exam: "Mid-Term Examination", subject: "Mathematics",      date: "14 Apr 2026", time: "9:00 AM – 12:00 PM", room: "Hall A" },
  { exam: "Mid-Term Examination", subject: "Physics",          date: "16 Apr 2026", time: "9:00 AM – 12:00 PM", room: "Hall B" },
  { exam: "Mid-Term Examination", subject: "Chemistry",        date: "18 Apr 2026", time: "9:00 AM – 12:00 PM", room: "Chem Lab" },
  { exam: "Mid-Term Examination", subject: "English",          date: "20 Apr 2026", time: "9:00 AM – 11:30 AM", room: "Hall A" },
  { exam: "Mid-Term Examination", subject: "History",          date: "22 Apr 2026", time: "9:00 AM – 11:30 AM", room: "Room 305" },
  { exam: "Mid-Term Examination", subject: "Computer Science", date: "24 Apr 2026", time: "9:00 AM – 11:00 AM", room: "Comp Lab" },
];

const PARENT_RESULTS = {
  examName: "Unit Test 3 (Feb 2026)",
  subjects: [
    { subject: "Mathematics",       marks: 87, max: 100, grade: "A",  remarks: "Good analytical skills" },
    { subject: "Physics",           marks: 79, max: 100, grade: "B+", remarks: "Needs more lab practice" },
    { subject: "English",           marks: 92, max: 100, grade: "A+", remarks: "Excellent creative writing" },
    { subject: "Chemistry",         marks: 74, max: 100, grade: "B",  remarks: "Improve organic concepts" },
    { subject: "History",           marks: 83, max: 100, grade: "A-", remarks: "Consistent performance" },
    { subject: "Computer Science",  marks: 96, max: 100, grade: "A+", remarks: "Outstanding" },
    { subject: "Physical Education",marks: 90, max: 100, grade: "A+", remarks: "Very active" },
  ],
  terms: [
    { term: "Term 1", pct: 82 },
    { term: "Unit Test 2", pct: 84 },
    { term: "Unit Test 3", pct: 86 },
  ]
};

const PARENT_MESSAGES = [
  { sender: "Prasana Reddy (Class Teacher)", subject: "KASULA ASHWATH's Math improvement", time: "Today 10:30 AM", unread: true, content: "KASULA ASHWATH has shown remarkable improvement in quadratic equations. Keep encouraging at home." },
  { sender: "School Admin", subject: "Parent-Teacher Meeting – April 5", time: "Yesterday", unread: true, content: "You are invited to the Q3 PTM on April 5, 2026 at 10 AM. Please confirm your attendance." },
  { sender: "Ramesh Sharma (Physics)", subject: "Lab report pending", time: "2 days ago", unread: false, content: "KASULA ASHWATH has not submitted the Newton's Laws lab report. Kindly ensure timely submission." },
  { sender: "Accounts Dept", subject: "Fee reminder – April installment", time: "3 days ago", unread: false, content: "A reminder that ₹10,000 is due by 5th April 2026. Ignore if already paid." },
];


// --- REMOVED OLD PARENT_FEE_HISTORY ---


// ─── Teacher Specific Mock Data ───────────────────────────────

const TEACHER_MY_CLASSES = [
  { class: "10-A", section: "Senior Secondary", subject: "Mathematics", students: 35, avgAtt: 95, avgPerf: "8.9 GPA", role: "Class Teacher" },
  { class: "9-B",  section: "Senior Secondary", subject: "Mathematics", students: 32, avgAtt: 91, avgPerf: "8.1 GPA", role: "Subject Teacher" },
  { class: "8-C",  section: "Middle School",    subject: "Mathematics", students: 28, avgAtt: 94, avgPerf: "8.5 GPA", role: "Subject Teacher" },
  { class: "10-B", section: "Senior Secondary", subject: "Substitution", students: 30, avgAtt: 88, avgPerf: "—",     role: "Substitute" },
];

const TEACHER_ATT_MARKING = [
  { roll: 7, name: "KASULA ASHWATH", status: "Present", last5: ["Present", "Present", "Absent", "Present", "Present"] },
  { roll: 1, name: "PRANEETH BHUKYA", status: "Present", last5: ["Present", "Present", "Present", "Present", "Present"] },
  { roll: 3, name: "KOTHA ASHVIK", status: "Present", last5: ["Late", "Present", "Present", "Present", "Present"] },
  { roll: 2, name: "SATHWIK REDDY GANTA", status: "", last5: ["Present", "Absent", "Absent", "Present", "Present"] },
  { roll: 8, name: "SNITHIK VENGALA", status: "", last5: ["Present", "Present", "Present", "Present", "Present"] },
  { roll: 9, name: "NIDHISH DUMALA", status: "", last5: ["Absent", "Delayed", "Present", "Present", "Present"] },
];

const TEACHER_HOMEWORK_TRACKING = [
  { id: "HW01", title: "Quadratic Equations – Practice Set", class: "10-A", dueDate: "Today",   status: "Submission Open", submitted: 28, pending: 7 },
  { id: "HW02", title: "Trigonometry Basics – Worksheet",    class: "9-B",  dueDate: "Tomorrow",status: "Submission Open", submitted: 15, pending: 17 },
  { id: "HW03", title: "Linear Equations Unit Test Prep",    class: "10-A", dueDate: "Yesterday",status: "Grading",       submitted: 34, pending: 1 },
  { id: "HW04", title: "Polynomials Case Study",             class: "8-C",  dueDate: "25 Mar",  status: "Graded",        submitted: 28, pending: 0 },
];

const TEACHER_RESULT_TRACKING = [
  { exam: "Unit Test 3", class: "10-A", subject: "Mathematics", totalStudents: 35, marksEntered: 35, avgScore: 88, status: "Submitted to VP" },
  { exam: "Unit Test 3", class: "9-B",  subject: "Mathematics", totalStudents: 32, marksEntered: 15, avgScore: 74, status: "Draft (In Progress)" },
  { exam: "Mid-Term",    class: "10-A", subject: "Mathematics", totalStudents: 35, marksEntered: 0,  avgScore: 0,  status: "Pending Entry" },
];

const TEACHER_STUDENT_PERF = [
  { name: "KASULA ASHWATH",   class: "9-C", att: 94, gpa: 8.7, trend: "up",   remark: "Consistent improvement." },
  { name: "PRANEETH BHUKYA", class: "9-C",  att: 98, gpa: 9.8, trend: "flat", remark: "Exceptional." },
  { name: "G MANASWINI",     class: "9-C",  att: 74, gpa: 6.2, trend: "down", remark: "Needs extra support." },
  { name: "BHUKYA PRANAVI",  class: "9-C",  att: 92, gpa: 8.8, trend: "up",   remark: "Good participation." },
  { name: "SNITHIK VENGALA", class: "9-C",  att: 82, gpa: 7.1, trend: "flat", remark: "Needs pushing in Algebra." },
];

const ANNOUNCEMENTS = [
  { id: 1, title: "Annual Sports Day – April 12, 2026", date: "28 Mar 2026", author: "Vice Principal", priority: "high", category: "General" },
  { id: 2, title: "Mid-Term Examination Schedule Released", date: "26 Mar 2026", author: "Coordinator", priority: "high", category: "Exam" },
  { id: 3, title: "Parent-Teacher Meeting – April 5", date: "24 Mar 2026", author: "Vice Principal", priority: "medium", category: "Meeting" },
  { id: 4, title: "Fee Payment Deadline – March 31", date: "22 Mar 2026", author: "Accounts Dept", priority: "high", category: "Finance" },
  { id: 5, title: "Library Hours Extended for Board Students", date: "20 Mar 2026", author: "Librarian", priority: "low", category: "Library" },
  { id: 6, title: "School Closed on April 14 (Ambedkar Jayanti)", date: "19 Mar 2026", author: "Admin", priority: "low", category: "Holiday" },
  { id: 7, title: "Science Exhibition Registration Open", date: "18 Mar 2026", author: "Coordinator", priority: "medium", category: "Event" },
];

const HOMEWORK = [
  { id: 1, title: "Quadratic Equations – Practice Set A", subject: "Mathematics", class: "10-A", teacher: "Prasana Reddy", due: "31 Mar 2026", submitted: 28, total: 35, status: "Active" },
  { id: 2, title: "Newton's Laws – Lab Report", subject: "Physics", class: "10-A", teacher: "Ramesh Sharma", due: "2 Apr 2026", submitted: 20, total: 35, status: "Active" },
  { id: 3, title: "The Tempest – Character Analysis Essay", subject: "English", class: "8-B", teacher: "Anita Pillai", due: "5 Apr 2026", submitted: 18, total: 32, status: "Active" },
  { id: 4, title: "Periodic Table Quiz", subject: "Chemistry", class: "10-C", teacher: "Mohan Das", due: "28 Mar 2026", submitted: 33, total: 33, status: "✅ Completed" },
  { id: 5, title: "World War II Summary", subject: "History", class: "7-A", teacher: "Sunita Verma", due: "7 Apr 2026", submitted: 5, total: 28, status: "Active" },
  { id: 6, title: "Python Basics – Program Set 1", subject: "Comp. Sci", class: "9-C", teacher: "Venkat Iyer", due: "10 Apr 2026", submitted: 0, total: 32, status: "Active" },
];

const SCHEDULE = [
  { time: "8:00–8:45", subject: "Mathematics", class: "10-A", teacher: "Prasana Reddy", room: "Room 101", color: "#5ca870" },
  { time: "8:50–9:35", subject: "Physics", class: "10-A", teacher: "Ramesh Sharma", room: "Physics Lab", color: "#1976d2" },
  { time: "9:40–10:25", subject: "English Literature", class: "8-B", teacher: "Anita Pillai", room: "Room 204", color: "#8b5cf6" },
  { time: "10:30–10:45", subject: "☕ Break", class: "—", teacher: "—", room: "—", color: "#999" },
  { time: "10:45–11:30", subject: "Chemistry", class: "10-C", teacher: "Mohan Das", room: "Chem Lab", color: "#f57c00" },
  { time: "11:35–12:20", subject: "History", class: "7-A", teacher: "Sunita Verma", room: "Room 305", color: "#e53935" },
  { time: "12:25–13:10", subject: "🍱 Lunch Break", class: "—", teacher: "—", room: "Cafeteria", color: "#999" },
  { time: "13:15–14:00", subject: "Computer Science", class: "9-C", teacher: "Venkat Iyer", room: "Comp Lab", color: "#00bcd4" },
  { time: "14:05–14:50", subject: "Biology", class: "8-E", teacher: "Pooja Mehta", room: "Bio Lab", color: "#4caf50" },
  { time: "14:55–15:40", subject: "Physical Education", class: "All", teacher: "Suresh Naidu", room: "Ground", color: "#ff5722" },
];

const EVENTS = [
  { title: "Annual Sports Day", date: "Apr 12, 2026", desc: "Inter-class athletics, team sports, prize ceremony", color: "#5ca870" },
  { title: "Science Exhibition", date: "Apr 18, 2026", desc: "Students showcase science projects", color: "#1976d2" },
  { title: "Parent-Teacher Meeting", date: "Apr 5, 2026", desc: "Quarterly academic progress discussion", color: "#f57c00" },
  { title: "Cultural Fest – Utsav 2026", date: "May 3, 2026", desc: "Music, dance & drama", color: "#8b5cf6" },
  { title: "Career Guidance Workshop", date: "May 10, 2026", desc: "Expert guidance for Class 9 & 10", color: "#00bcd4" },
  { title: "Summer Vacation Begins", date: "May 20, 2026", desc: "School closes for summer break", color: "#e53935" },
];

const VP_APPROVALS = [
  { id: "AP01", title: "Leave Request", desc: "Medical leave – Anita Pillai", status: "Pending" },
  { id: "AP02", title: "Timetable Swap", desc: "Swap P3 with Prasana Reddy", status: "Pending" },
  { id: "AP03", title: "Event Fund", desc: "₹15,000 for Science Exhibition", status: "Pending" },
  { id: "AP04", title: "Result Release", desc: "Mid-Term results for Class 8-B", status: "✅ Approved" },
  { id: "AP05", title: "Notice Draft", desc: "Summer Vacation Schedule Review", status: "Pending" },
];

const CLASS_PERFORMANCE = [
  { class: "10-A", teacher: "Prasana Reddy", att: 95, gpa: 8.9, topper: "PRANEETH BHUKYA", weak: 2, issues: 3 },
  { class: "10-B", teacher: "Ramesh Sharma", att: 92, gpa: 8.2, topper: "Karan Johar", weak: 4, issues: 5 },
  { class: "10-C", teacher: "Mohan Das", att: 88, gpa: 7.6, topper: "Rahul G.", weak: 6, issues: 8 },
  { class: "9-A", teacher: "Anita Pillai", att: 91, gpa: 8.4, topper: "Sneha P.", weak: 3, issues: 2 },
  { class: "9-B", teacher: "Venkat Iyer", att: 81, gpa: 7.1, topper: "KASULA ASHWATH", weak: 7, issues: 4 },
  { class: "8-A", teacher: "Sunita Verma", att: 93, gpa: 8.0, topper: "SNITHIK VENGALA", weak: 2, issues: 1 },
  { class: "8-B", teacher: "Pooja Mehta", att: 85, gpa: 7.4, topper: "G MANASWINI", weak: 5, issues: 6 },
  { class: "7-A", teacher: "Suresh Naidu", att: 96, gpa: 9.1, topper: "BHUKYA PRANAVI", weak: 1, issues: 0 },
  { class: "6-A", teacher: "Prasana Reddy", att: 92, gpa: 8.5, topper: "Ravi K.", weak: 4, issues: 3 },
];

const PARENT_FEE_HISTORY = [
  { date: "15 Mar 2026", desc: "Tuition Fee (Q3)", amount: 30000, mode: "Online", status: "Paid" },
  { date: "15 Mar 2026", desc: "Lab Fee", amount: 5000, mode: "Online", status: "Paid" },
  { date: "15 Mar 2026", desc: "Transport Fee (Q3)", amount: 5000, mode: "Online", status: "Paid" },
  { date: "Pending", desc: "Library Fee", amount: 2000, mode: "—", status: "Due" },
  { date: "Pending", desc: "Sports Fee", amount: 3000, mode: "—", status: "Due" },
];

const DEFAULT_GLOBAL_ISSUES = [
  {
    id: "ISS-1001",
    title: "Bus route 4 arriving late",
    desc: "The bus driver has been arriving 15 minutes late for the past week, making the student late for morning assembly.",
    status: "Reviewing",
    stage: "Coordinator",
    studentId: "3180076",
    studentName: "KASULA ASHWATH",
    class: "9-C",
    reporterId: "P3180076A",
    reporterName: "Parent of KASULA ASHWATH",
    reporterRole: "Parent",
    category: "Transport",
    priority: "Medium",
    severity: "Normal",
    assignedTo: "Anitha (Coord)",
    attachments: [],
    created: "2026-03-25T08:30:00Z",
    updated: "2026-03-28T09:15:00Z",
    timeline: [
      { date: "2026-03-25T08:30:00Z", actor: "Parent of KASULA ASHWATH", role: "Parent", note: "Issue raised regarding bus delays." },
      { date: "2026-03-26T10:00:00Z", actor: "Prasana Reddy", role: "Teacher", note: "I have also noticed the student arriving late. Escalated to Transport/Coordinator." },
      { date: "2026-03-26T10:05:00Z", actor: "System", role: "System", note: "Escalated to Coordinator" },
      { date: "2026-03-28T09:15:00Z", actor: "Anitha", role: "Coordinator", note: "I am speaking with the fleet manager to review GPS logs for Route 4." }
    ]
  },
  {
    id: "ISS-1002",
    title: "Discipline issue during P.E.",
    desc: "Student was involved in a minor altercation during the basketball match.",
    status: "Pending Action",
    stage: "VP",
    studentId: "3240214",
    studentName: "NIMMAKAYALA PRATEEK REDDY",
    class: "9-C",
    reporterId: "C001",
    reporterName: "Anitha",
    reporterRole: "Coordinator",
    category: "Discipline",
    priority: "High",
    severity: "Critical",
    assignedTo: "VP Suman",
    attachments: [],
    created: "2026-03-29T11:00:00Z",
    updated: "2026-03-29T14:30:00Z",
    timeline: [
      { date: "2026-03-29T11:00:00Z", actor: "Anitha", role: "Coordinator", note: "Reported altercation during PE. Immediate VP attention required." },
      { date: "2026-03-29T11:05:00Z", actor: "System", role: "System", note: "Escalated to VP" }
    ]
  }
];

function initDataStore() {
  const DATA_VERSION = '1.1';
  if (localStorage.getItem('campuscore_version') !== DATA_VERSION) {
    localStorage.removeItem('campuscore_issues');
    localStorage.removeItem('campuscore_students');
    localStorage.removeItem('campuscore_escalations');
    localStorage.setItem('campuscore_version', DATA_VERSION);
  }

  if (!localStorage.getItem('campuscore_issues')) {
    localStorage.setItem('campuscore_issues', JSON.stringify(DEFAULT_GLOBAL_ISSUES));
  }
  GLOBAL_ISSUES = JSON.parse(localStorage.getItem('campuscore_issues'));
  
  if (!localStorage.getItem('campuscore_settings')) {
    localStorage.setItem('campuscore_settings', JSON.stringify({}));
  }
  
  // Persist STUDENTS to support Promote feature
  if (!localStorage.getItem('campuscore_students')) {
    localStorage.setItem('campuscore_students', JSON.stringify(STUDENTS));
  } else {
    STUDENTS = JSON.parse(localStorage.getItem('campuscore_students'));
  }

  // --- NEW FEATURE INITIALIZATION ---
  if (!localStorage.getItem('campuscore_documents')) {
    localStorage.setItem('campuscore_documents', JSON.stringify([
      { id: 'DOC-001', title: 'Annual Day Circular', class: 'All Classes', subject: 'General', type: 'Circular', date: '2026-03-20', author: 'Principal' },
      { id: 'DOC-002', title: 'Maths Unit Test Notes', class: '9C', subject: 'Mathematics', type: 'Notes', date: '2026-04-01', author: 'Ramesh Sharma' }
    ]));
  }
  if (!localStorage.getItem('campuscore_student_requests')) {
    localStorage.setItem('campuscore_student_requests', JSON.stringify([
      { id: 'REQ-882', title: 'Leave Application', studentId: '3180076', studentName: 'KASULA ASHWATH', type: 'Leave', status: 'Pending', stage: 'Teacher', date: '2026-04-10' }
    ]));
  }
  if (!localStorage.getItem('campuscore_helpdesk_tickets')) {
    localStorage.setItem('campuscore_helpdesk_tickets', JSON.stringify([
      { id: 'TKT-101', studentName: 'KASULA ASHWATH', subject: 'Library Book Missing', status: 'Open', priority: 'Medium', lastUpdate: '2026-04-09', assignedTo: 'Librarian' }
    ]));
  }
}

function saveStudents() {
  localStorage.setItem('campuscore_students', JSON.stringify(STUDENTS));
}


function saveIssues(issuesArr) {
  GLOBAL_ISSUES = issuesArr;
  localStorage.setItem('campuscore_issues', JSON.stringify(GLOBAL_ISSUES));
}

function getSettings(userId) {
  const allSet = JSON.parse(localStorage.getItem('campuscore_settings') || '{}');
  return allSet[userId] || {
    darkMode: false,
    compactMode: false,
    emailNotif: true,
    attNotif: true,
    feeNotif: false,
    hwNotif: true,
    language: 'English',
    twoFactor: false
  };
}

function saveSettings(userId, settingsObj) {
  const allSet = JSON.parse(localStorage.getItem('campuscore_settings') || '{}');
  allSet[userId] = settingsObj;
  localStorage.setItem('campuscore_settings', JSON.stringify(allSet));
}

initDataStore();
